server_port: "8000"
discord:
  webhook_id: "1143500994299310092"
  token: "QjQr2LewR9tqc-BFxjgPFFmyfPfhDe-HHRdvSDluu1rYzGaoTIwuJ70dJDDLko4Aycca"
  sql_webhook_id: "1143732644035690556"
  sql_token: "89Tu2JYkOkGuPMRr1yQAfSq1r_zuokr-nYdyNgwRxE78rpU55Ii3Ro5R6eOmlZEwGK9G"
database:
  postgres:
    host: "0.0.0.0"
    user: "postgres"
    dbname: "postgres"
    port: "5432"
    password: "boatboat224"
    search_path: "my_go_dev"
    sslmode: "disable"
  mongodb:
    uri: "mongodb://localhost:27017/my_go_dev"
jwt_secret: "skdlng9204u5yh34ljkvkwretwubo"